//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestiary
    {
        public int BestiaryId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CR { get; set; }
        public Nullable<int> XP { get; set; }
        public string Race { get; set; }
        public string Class { get; set; }
        public string Alignment { get; set; }
        public string Size { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
        public Nullable<int> Init { get; set; }
        public string Senses { get; set; }
        public string Aura { get; set; }
        public string AC { get; set; }
        public string ACMods { get; set; }
        public Nullable<int> HP { get; set; }
        public string HD { get; set; }
        public string HPMods { get; set; }
        public Nullable<int> Fortitude { get; set; }
        public Nullable<int> Reflex { get; set; }
        public Nullable<int> Will { get; set; }
        public string SaveMods { get; set; }
        public string DefensiveAbilities { get; set; }
        public string DR { get; set; }
        public string Immune { get; set; }
        public string Resist { get; set; }
        public Nullable<int> SR { get; set; }
        public string Weaknesses { get; set; }
        public string Speed { get; set; }
        public string SpeedMod { get; set; }
        public string Melee { get; set; }
        public string Ranged { get; set; }
        public string Space { get; set; }
        public string Reach { get; set; }
        public string SpecialAttacks { get; set; }
        public string SpellLikeAbilities { get; set; }
        public string SpellsKnown { get; set; }
        public string SpellsPrepared { get; set; }
        public string SpellDomains { get; set; }
        public string AbilityScores { get; set; }
        public string AbilityScoreMods { get; set; }
        public Nullable<int> BaseAtk { get; set; }
        public Nullable<int> CMB { get; set; }
        public Nullable<int> CMD { get; set; }
        public string Feats { get; set; }
        public string Skills { get; set; }
        public string RacialMods { get; set; }
        public string Languages { get; set; }
        public string SQ { get; set; }
        public string Environment { get; set; }
        public string Organization { get; set; }
        public string Treasure { get; set; }
        public string DescriptionVisual { get; set; }
        public string Group { get; set; }
        public Nullable<bool> IsTemplate { get; set; }
        public string SpecialAbilities { get; set; }
        public string Gender { get; set; }
        public string Bloodline { get; set; }
        public string ProhibitedSchools { get; set; }
        public string BeforeCombat { get; set; }
        public string DuringCombat { get; set; }
        public string Morale { get; set; }
        public string Gear { get; set; }
        public string OtherGear { get; set; }
        public string Vulnerability { get; set; }
        public string Note { get; set; }
        public Nullable<bool> CharacterFlag { get; set; }
        public Nullable<bool> CompanionFlag { get; set; }
        public Nullable<bool> Fly { get; set; }
        public Nullable<bool> Climb { get; set; }
        public Nullable<bool> Burrow { get; set; }
        public Nullable<bool> Swim { get; set; }
        public Nullable<bool> Land { get; set; }
        public string TemplatesApplied { get; set; }
        public string OffenseNote { get; set; }
        public string BaseStatistics { get; set; }
        public string ExtractsPrepared { get; set; }
        public string AgeCategory { get; set; }
        public Nullable<bool> DontUseRacialHD { get; set; }
        public string VariantParent { get; set; }
        public string Mystery { get; set; }
        public string ClassArchetypes { get; set; }
        public string Patron { get; set; }
        public string CompanionFamiliarLink { get; set; }
        public string FocusedSchool { get; set; }
        public string Traits { get; set; }
        public string AlternateNameForm { get; set; }
        public string StatisticsNote { get; set; }
        public string LinkText { get; set; }
        public Nullable<bool> UniqueMonster { get; set; }
        public Nullable<int> MR { get; set; }
        public Nullable<bool> Mythic { get; set; }
        public Nullable<int> MT { get; set; }
        public Nullable<int> ACTouch { get; set; }
        public Nullable<int> ACFlat { get; set; }
        public Nullable<int> STR { get; set; }
        public Nullable<int> DEX { get; set; }
        public Nullable<int> CON { get; set; }
        public Nullable<int> WIS { get; set; }
        public Nullable<int> INT { get; set; }
        public Nullable<int> CHA { get; set; }
    }
}
