//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonsterSpawn
    {
        public int SpawnId { get; set; }
        public Nullable<int> Continent { get; set; }
        public Nullable<int> Season { get; set; }
        public Nullable<int> BestiaryId { get; set; }
    }
}
